source 'https://rubygems.org'

gem 'rails', '4.2.4'

group :test do
  gem 'brakeman'                  # Always latest
  gem 'cane',                     '2.6.2'
  gem 'capybara',                 '2.4.1'
  gem 'database_cleaner',         '1.5.1'
  gem 'factory_girl',             '4.5.0'
  gem 'ffaker',                   '1.32.1'
  gem 'rspec-its',                '1.0.1'
  gem 'rspec-rails',              '3.2.1'
  gem 'rspec',                    '3.2.0'
  gem 'scss-lint',                '~> 0.37.0'
  gem 'tailor',                   '1.4.1'
end

group :development do
  gem 'spring'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
end